---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - {
              dir: "build_debug",
              build_type: "Debug"
            }
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v2.3.4

      - name: ⤵️ Check out nanopb
        uses: actions/checkout@v2.3.4
        with:
          repository: nanopb/nanopb
          ref: nanopb-0.4.5
          path: 'nanopb_src'

      - name: Setup build vars
        run: echo '::set-output name=BUILD_DIR::build_${{ matrix.config.dir }}'
        id: build_vars

      - name:  🚀 Run unit tests
        uses: HorstBaerbel/action-ctest@1.1
        with:
          sourcedir: '.'
          builddir: ${{ steps.build_vars.outputs.BUILD_DIR }}
          cmakeoptions: |
            -DCMAKE_BUILD_TYPE="${{ matrix.config.build_type }}" \
            -DNANOPB_ROOT="nanopb_src"
          ctestoptions: ''

